"""updated books_controller

Revision ID: 25dbde26a23f
Revises: f99d3cb9fd17
Create Date: 2024-04-17 16:14:02.542714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25dbde26a23f'
down_revision = 'f99d3cb9fd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('publication_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('publication_date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
